import { z } from "zod";

// export const createResultFormSchema = z.object({
//     queryInformationLT: z.any(),
//     queryInformationStandard: z.any(),
//     serviceResults: z.any(),
// });
export const createResultFormSchema = z.object({
    queryInformationLTFullName: z.string().optional(),
    queryInformationLTIndexNo: z.number().optional(),
    queryInformationLTAddress: z.string().optional(),
    queryInformationLTBusinessName: z.string().optional(),
    queryInformationLTInputDate: z.string().optional(),
    queryInformationStandardServeTo: z.string().optional(),
    queryInformationStandardDefendants: z.string().optional(),
    serviceResultInputDate: z.string().optional(),
    serviceResultScvType: z.string().optional(),
    serviceResultClientId: z.string().optional(),
    serviceResultJobNo: z.number(),
    serviceResultServerId: z.string().optional(),
    serviceResultResults: z.string().optional(),
    serviceResultDateOfService: z.string().optional(),
    serviceResultFirstTimeOfService: z.string().optional(),
    serviceResultFirstAttemptDate: z.string().optional(),
    serviceResultSecondTimeOfService: z.string().optional(),
    serviceResultSecondAttemptDate: z.string().optional(),
    serviceResultThirdTimeOfService: z.string().optional(),
    serviceResultThirdAttemptDate: z.string().optional(),
    serviceResultlTServed: z.string().optional(),
    serviceResultlTNotServed: z.string().optional(),
    serviceResultRecipientTitle: z.string().optional(),
    serviceResultDoor: z.number().optional().nullable(),
    serviceResultDoorLocks: z.number().optional().nullable(),
    serviceResultEntry: z.number().optional().nullable(),
    serviceResultWall: z.number().optional().nullable(),
    serviceResultFloor: z.number().optional().nullable(),
    serviceResultLock: z.number().optional().nullable(),
    serviceResultOtherDescription: z.boolean().optional(),
    serviceResultSex: z.string().optional(),
    serviceResultSkinColor: z.string().optional(),
    serviceResultHair: z.string().optional(),
    serviceResultAge: z.number().optional().nullable(),
    serviceResultHeight: z.number().optional().nullable(),
    serviceResultWeight: z.number().optional().nullable(),
    serviceResultOtherFeatures: z.string().optional(),
    serviceResultDateOfMailing: z.string().optional(),
    serviceResultDateOfNotary: z.string().optional(),
});