import { z } from "zod";

export const createServiceFormSchema = z.object({
    jobNo: z.number().optional(),
    inputDate: z.string().optional(),
    clientId: z.number().optional(),
    serviceType: z.number().optional(),
    caseNo: z.number().optional(),
    caption: z.string().optional(),
    lTServiceType: z.number().optional(),
    // otherLTServiceTypeData: z.number().optional(),
    oLTIndexNo: z.number().optional(),
    oLTDescription: z.string().optional(),
    // lTServiceDetail: z.number().optional(),
    lTSFirstName: z.string().optional(),
    lTSBusinessName: z.string().optional(),
    lTSZip: z.string().optional(),
    lTSState: z.string().optional(),
    lTSCity: z.string().optional(),
    lTSApt: z.string().optional(),
    lTSAddress: z.string().optional(),
    lTSDescription: z.string().optional(),
    noOfAddLMailings: z.number().optional(),
    mailingAddresses: z.string().optional(),
    standardServiceType: z.string().optional(),
    // otherStandardServiceTypeData: z.number().optional(),
    oSSTIndexNo: z.number().optional(),
    oSSTDescription: z.string().optional(),
    // standardServiceDetail: z.number().optional(),
    sSDCourt: z.string().optional(),
    sSDDefendants: z.string().optional(),
    sSDPlaintiff: z.string().optional(),
    sSDCountry: z.string().optional(),
    //Serve to
    firstNameServe: z.string().optional(),
    addressServe: z.string().optional(),
    cityServe: z.string().optional(),
    stateServe: z.string().optional(),
    aptServe: z.string().optional(),
    zipServe: z.string().optional(),
    serviceFormCreatedBy: z.string().optional(),
    lastUpdatedBy:z.string().optional()
});