import { z } from "zod";

const mailingAddressSchema = z.object({
    address:z.string().optional(),
    apt:z.string().optional(),
    city:z.string().optional(),
    createdAt:z.string().optional(),
    firstName:z.string().optional(),
    rRR:z.boolean().optional(),
    state:z.string().optional(),
    updatedAt:z.string().optional(),
    zip:z.any().optional(),
    __v:z.any().optional(),
    _id:z.any().optional(),
  });

export const createServiceFormSchema = z.object({
    jobNo: z.number().optional(),
    inputDate: z.string().optional(),
    clientId: z.any().optional(),
    serviceType: z.any().optional(),
    caseNo: z.number().optional(),
    caption: z.string().optional(),
    lTServiceType: z.any().optional(),
    // otherLTServiceTypeData: z.number().optional(),
    oLTIndexNo: z.any().optional(),
    oLTDescription: z.string().optional(),
    // lTServiceDetail: z.number().optional(),
    lTSFirstName: z.string().optional(),
    lTSBusinessName: z.string().optional(),
    lTSZip: z.string().optional(),
    lTSState: z.string().optional(),
    lTSCity: z.string().optional(),
    lTSApt: z.string().optional(),
    lTSAddress: z.string().optional(),
    lTSDescription: z.string().optional(),
    noOfAddLMailings: z.number().optional(),
    mailingAddresses:z.array(mailingAddressSchema).optional(),
    standardServiceType: z.any().optional(),
    // otherStandardServiceTypeData: z.number().optional(),
    oSSTIndexNo: z.any().optional(),
    oSSTDescription: z.string().optional(),
    // standardServiceDetail: z.number().optional(),
    sSDCourt: z.string().optional(),
    sSDDefendants: z.string().optional(),
    sSDPlaintiff: z.string().optional(),
    sSDCountry: z.string().optional(),
    //Serve to
    // firstNameServe: z.string().optional(),
    // addressServe: z.string().optional(),
    // cityServe: z.string().optional(),
    // stateServe: z.string().optional(),
    // aptServe: z.string().optional(),
    // zipServe: z.string().optional(),
    // serviceFormCreatedBy: z.string().optional(),
    // lastUpdatedBy:z.string().optional()
});