import { z } from "zod";

const mailingAddressSchema = z.object({
  address: z.string().optional(),
  apt: z.string().optional(),
  city: z.string().optional(),
  createdAt: z.string().optional(),
  firstName: z.string().optional(),
  rRR: z.boolean().optional(),
  state: z.string().optional(),
  updatedAt: z.string().optional(),
  zip: z.any().optional(),
  __v: z.any().optional(),
  _id: z.any().optional(),
});

export const createServiceFormSchema = z.object({
  jobNo: z.number().optional(),
  inputDate: z.string().optional(),
  clientId: z.any().optional(),
  serviceType: z.any().optional(),
  caseNo: z.any().optional(),
  caption: z.string().optional(),
  lTServiceType: z.any().optional(),
  oLTIndexNo: z.any().optional(),
  oLTDescription: z.string().optional(),
  lTSFirstName: z.string().optional(),
  lTSBusinessName: z.string().optional(),
  lTSZip: z.string().optional(),
  lTSState: z.string().optional(),
  lTSCity: z.string().optional(),
  lTSApt: z.string().optional(),
  lTSAddress: z.string().optional(),
  lTSDescription: z.string().optional(),
  noOfAddLMailings: z.number().optional(),
  mailingAddresses: z.array(mailingAddressSchema).optional(),
  standardServiceType: z.any().optional(),
  oSSTIndexNo: z.any().optional(),
  oSSTDescription: z.string().optional(),
  sSDCourt: z.string().optional(),
  sSDDefendants: z.string().optional(),
  sSDPlaintiff: z.string().optional(),
  sSDCountry: z.string().optional(),

  //Result Form Attributes
  queryInformationLTFullName: z.string().optional(),
  queryInformationLTIndexNo: z.number().optional(),
  queryInformationLTAddress: z.string().optional(),
  queryInformationLTBusinessName: z.string().optional(),
  queryInformationLTInputDate: z.string().optional(),
  queryInformationStandardServeTo: z.string().optional(),
  queryInformationStandardDefendants: z.string().optional(),
  serviceResultInputDate: z.string().optional(),
  serviceResultScvType: z.string().optional(),
  serviceResultClientId: z.string().optional(),
  serviceResultJobNo: z.number().optional(),
  serviceResultServerId: z.string().optional(),
  serviceResultResults: z.string().optional(),
  serviceResultDateOfService: z.string().optional(),
  serviceResultFirstTimeOfService: z.string().optional(),
  serviceResultFirstAttemptDate: z.string().optional(),
  serviceResultSecondTimeOfService: z.string().optional(),
  serviceResultSecondAttemptDate: z.string().optional(),
  serviceResultThirdTimeOfService: z.string().optional(),
  serviceResultThirdAttemptDate: z.string().optional(),
  serviceResultlTServed: z.string().optional(),
  serviceResultlTNotServed: z.string().optional(),
  serviceResultSubstitudeDeliveredTo: z.string().optional(),
  serviceResultRecipientTitle: z.string().optional(),
  serviceResultRecipient: z.string().optional(),
  serviceResultDoor: z.number().optional().nullable(),
  serviceResultDoorLocks: z.number().optional().nullable(),
  serviceResultEntry: z.number().optional().nullable(),
  serviceResultWall: z.number().optional().nullable(),
  serviceResultFloor: z.number().optional().nullable(),
  serviceResultLock: z.number().optional().nullable(),
  serviceResultOtherDescription: z.boolean().optional(),
  serviceResultSex: z.string().optional(),
  serviceResultSkinColor: z.string().optional(),
  serviceResultHair: z.string().optional(),
  serviceResultAge: z.number().optional().nullable(),
  serviceResultHeight: z.number().optional().nullable(),
  serviceResultWeight: z.number().optional().nullable(),
  serviceResultOtherFeatures: z.string().optional(),
  serviceResultDateOfMailing: z.string().optional(),
  serviceResultDateOfNotary: z.string().optional(),
  serviceResultTimeOfService: z.string().optional(),

});