

export interface ICreateResultForm {
    queryInformationLTFullName?:string | null,
    queryInformationLTIndexNo?:number | null ,
    queryInformationLTAddress?:string | null ,
    queryInformationLTBusinessName?:string | null ,
    queryInformationLTInputDate?:string | null ,
    queryInformationStandardServeTo?:string | null ,
    queryInformationStandardDefendants?:string | null ,
    serviceResultInputDate?:string | null | null,
    serviceResultScvType?:string | null ,
    serviceResultClientId?:string | null ,
    serviceResultJobNo?:number | null ,
    serviceResultServerId?:string | null ,
    serviceResultResults?:string | null ,
    serviceResultDateOfService?:string | null ,
    serviceResultFirstTimeOfService?:string | null , 
    serviceResultFirstAttemptDate?:string | null ,
    serviceResultSecondTimeOfService?:string | null , 
    serviceResultSecondAttemptDate?:string | null ,  
    serviceResultThirdTimeOfService?:string | null , 
    serviceResultThirdAttemptDate?:string | null ,
    serviceResultlTServed?:string | null ,
    serviceResultlTNotServed?:string | null ,
    serviceResultRecipientTitle?:string | null ,
    serviceResultDoor?:number | null ,
    serviceResultDoorLocks?:number | null ,
    serviceResultEntry?:number | null ,
    serviceResultWall?:number | null ,
    serviceResultFloor?:number | null ,
    serviceResultLock?:number | null ,
    serviceResultOtherDescription?:string | null ,
    serviceResultSex?:string | null ,
    serviceResultSkinColor?:string | null ,
    serviceResultHair?:string | null ,
    serviceResultAge?:number | null ,
    serviceResultHeight?:number | null ,
    serviceResultWeight?:number | null ,
    serviceResultOtherFeatures?:string | null ,
    serviceResultDateOfMailing?:string | null ,
    serviceResultDateOfNotary?:string | null ,
}

export interface IUpdateResultForm extends ICreateResultForm {
    resultFormId: string
}