
export interface ICreateServiceForm {
    jobNo: number,
    inputDate: string,
    clientId: string,
    serviceType?: string,
    caseNo: number,
    caption?: string,
    lTServiceType?: string,
    oLTIndexNo?: any,
    oLTDescription?: string,
    lTSFirstName?: string,
    lTSBusinessName?: string,
    lTSZip?: string,
    lTSState?: string,
    lTSCity?: string,
    lTSApt?: string,
    lTSAddress?: string,
    lTSDescription?: string,
    noOfAddLMailings?: number,
    mailingAddresses?: any,
    standardServiceType?: any,
    oSSTIndexNo?: any,
    oSSTDescription?: string,
    sSDCourt?: string,
    sSDDefendants?: string,
    sSDPlaintiff?: string,
    sSDCountry?: string,

    //Result Form Attributes
    queryInformationLTFullName?: string | null | undefined,
    queryInformationLTIndexNo?: number | null | undefined,
    queryInformationLTAddress?: string | null | undefined,
    queryInformationLTBusinessName?: string | null | undefined,
    queryInformationLTInputDate?: string | null | undefined,
    queryInformationStandardServeTo?: string | null | undefined,
    queryInformationStandardDefendants?: string | null | undefined,
    serviceResultInputDate?: string | null | undefined | null | undefined,
    serviceResultScvType?: string | null | undefined,
    serviceResultClientId?: string | null | undefined,
    serviceResultJobNo?: number | null | undefined,
    serviceResultServerId?: string | null | undefined,
    serviceResultResults?: string | null | undefined,
    serviceResultDateOfService?: string | null | undefined,
    serviceResultFirstTimeOfService?: string | null | undefined,
    serviceResultFirstAttemptDate?: string | null | undefined,
    serviceResultSecondTimeOfService?: string | null | undefined,
    serviceResultSecondAttemptDate?: string | null | undefined,
    serviceResultThirdTimeOfService?: string | null | undefined,
    serviceResultThirdAttemptDate?: string | null | undefined,
    serviceResultlTServed?: string | null | undefined,
    serviceResultlTNotServed?: string | null | undefined,
    serviceResultSubstitudeDeliveredTo?: string | null | undefined,
    serviceResultRecipientTitle?: string | null | undefined,
    serviceResultRecipient?: string | null | undefined,
    serviceResultDoor?: number | null | undefined,
    serviceResultDoorLocks?: number | null | undefined,
    serviceResultEntry?: number | null | undefined,
    serviceResultWall?: number | null | undefined,
    serviceResultFloor?: number | null | undefined,
    serviceResultLock?: number | null | undefined,
    serviceResultOtherDescription?: boolean | null | undefined,
    serviceResultSex?: string | null | undefined,
    serviceResultSkinColor?: string | null | undefined,
    serviceResultHair?: string | null | undefined,
    serviceResultAge?: number | null | undefined,
    serviceResultHeight?: number | null | undefined,
    serviceResultWeight?: number | null | undefined,
    serviceResultOtherFeatures?: string | null | undefined,
    serviceResultDateOfMailing?: string | null | undefined,
    serviceResultDateOfNotary?: string | null | undefined,
    serviceResultTimeOfService?: string | null | undefined,
    substituteDeliveredTo?: string | null | undefined,
    corporateRecipient?: string | null | undefined,

}

export interface IUpdateServiceForm extends ICreateServiceForm {
    serviceFormId: string,
}